### ISSUE TITLE
I want to run a script on startup

### ISSUE THREAD

**Issue by gavacho** [tripviss/docker-varnish#20]
It is very nice to work with this docker image.  Thank you for maintaining.

I would like to execute a command before varnishd is started.  In my use-case, I would expand a templated vcl file with some environment variables.

I would be happy to submit a PR for this feature if you welcome one.

**Comment by teohhanhui** [comment]
Use your own `ENTRYPOINT` script.

For example:

```sh
#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- varnishd "$@"
fi

if [ "$1" = 'varnishd' ]; then
	mkdir -p /usr/local/etc/varnish
	confd --onetime --confdir /usr/local/etc/confd --backend env
fi

exec docker-varnish-entrypoint "$@"
```
